services:
  frontend:
    image: ghcr.io/upikoth/starter-vue3
    container_name: frontend
    ports:
      - 127.0.0.1:4001:80
    environment:
      API_URL: ${API_URL}
      SENTRY_DNS: ${SENTRY_DNS}
      S3_DOMAIN_NAME: ${S3_DOMAIN_NAME}
