name: Deploy

on:
  push:
    branches:
      - main

env:
  UPIKOTH_PACKAGES_READ: ${{ secrets.UPIKOTH_PACKAGES_READ }}

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - run: npm ci
      - run: npm run lint

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: npm ci
      - run: npm run build
      - run: rsync -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" --delete -r ./dist/ root@${{ secrets.SSH_HOST }}:${{ vars.APP_SERVER_PATH }}
